=== pavithra03042006/Web-Technology/6A-OnlineQuiz/XML/students.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="students">
<xs:complexType>
<xs:sequence>

<xs:element name="student" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>

<xs:element name="studentId" type="xs:string"/>
<xs:element name="name" type="xs:string"/>
<xs:element name="department" type="xs:string"/>
<xs:element name="semester" type="xs:integer"/>

<xs:element name="subjects">
<xs:complexType>
<xs:sequence>

<xs:element name="subject" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>

<xs:element name="subjectName" type="xs:string"/>
<xs:element name="marks" type="xs:integer"/>

</xs:sequence>
</xs:complexType>
</xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== pavithra03042006/Web-Technology/6A-OnlineQuiz/XML/students.xml
<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="students.xsl"?>

<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="students.xsd">

    <student>
        <studentId>S101</studentId>
        <name>Rahul</name>
        <department>CSE</department>
        <semester>5</semester>

        <subjects>
            <subject>
                <subjectName>DBMS</subjectName>
                <marks>85</marks>
            </subject>

            <subject>
                <subjectName>Java</subjectName>
                <marks>90</marks>
            </subject>
        </subjects>
    </student>

    <student>
        <studentId>S102</studentId>
        <name>Anjali</name>
        <department>IT</department>
        <semester>4</semester>

        <subjects>
            <subject>
                <subjectName>CN</subjectName>
                <marks>88</marks>
            </subject>

            <subject>
                <subjectName>Python</subjectName>
                <marks>92</marks>
            </subject>
        </subjects>
    </student>

</students>
